server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
security:
  jwt:
    secret: huhgsth898hrfroijjjjjjjjjjjjjjfdspoijfpasjfdifjsif_TODO_CHANGE
    expiration-ms: 3600000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    com.microservices.cart: DEBUG
